export default [
  {
    image: require('./assets/images/Barrel.png'),
    name: 'Beer Barrel',
    category: 'Beer',
    price: 200,
    availableInNoOfBars: 6,
  },
  {
    image: require('./assets/images/twoGlassWine.png'),
    name: 'Red Wine',
    category: 'Wine',
    price: 800,
    availableInNoOfBars: 5,
  },
  {
    image: require('./assets/images/champane.png'),
    name: 'Champagne',
    category: 'Extra brut',
    price: 4000,
    availableInNoOfBars: 3,
  },
  {
    image: require('./assets/images/alcohol.png'),
    name: 'Pint',
    category: 'Beer',
    price: 100,
    availableInNoOfBars: 50,
  },
  {
    image: require('./assets/images/alcoholic-drinks.png'),
    name: 'Wine Canister',
    category: 'Wine',
    price: 6000,
    availableInNoOfBars: 10,
  },
  {
    image: require('./assets/images/arak.png'),
    name: 'Arak',
    category: 'Wine',
    price: 600,
    availableInNoOfBars: 12,
  },
  {
    image: require('./assets/images/beer.png'),
    name: 'Beer Mug',
    category: 'Beer',
    price: 150,
    availableInNoOfBars: 16,
  },
  {
    image: require('./assets/images/cocktail.png'),
    name: 'Cocktail',
    category: 'Sweet Drink',
    price: 200,
    availableInNoOfBars: 14,
  },
  {
    image: require('./assets/images/Barrel.png'),
    name: 'Beer Barrel',
    category: 'Beer',
    price: 200,
    availableInNoOfBars: 6,
  },
  {
    image: require('./assets/images/twoGlassWine.png'),
    name: 'Red Wine',
    category: 'Wine',
    price: 800,
    availableInNoOfBars: 5,
  },
  {
    image: require('./assets/images/champane.png'),
    name: 'Champagne',
    category: 'Extra brut',
    price: 4000,
    availableInNoOfBars: 3,
  },
  {
    image: require('./assets/images/alcohol.png'),
    name: 'Pint',
    category: 'Beer',
    price: 100,
    availableInNoOfBars: 50,
  },
  {
    image: require('./assets/images/alcoholic-drinks.png'),
    name: 'Wine Canister',
    category: 'Wine',
    price: 6000,
    availableInNoOfBars: 10,
  },
  {
    image: require('./assets/images/arak.png'),
    name: 'Arak',
    category: 'Wine',
    price: 600,
    availableInNoOfBars: 12,
  },
  {
    image: require('./assets/images/beer.png'),
    name: 'Beer Mug',
    category: 'Beer',
    price: 150,
    availableInNoOfBars: 16,
  },
  {
    image: require('./assets/images/cocktail.png'),
    name: 'Cocktail',
    category: 'Sweet Drink',
    price: 200,
    availableInNoOfBars: 14,
  },
  {
    image: require('./assets/images/Barrel.png'),
    name: 'Beer Barrel',
    category: 'Beer',
    price: 200,
    availableInNoOfBars: 6,
  },
  {
    image: require('./assets/images/twoGlassWine.png'),
    name: 'Red Wine',
    category: 'Wine',
    price: 800,
    availableInNoOfBars: 5,
  },
  {
    image: require('./assets/images/champane.png'),
    name: 'Champagne',
    category: 'Extra brut',
    price: 4000,
    availableInNoOfBars: 3,
  },
  {
    image: require('./assets/images/alcohol.png'),
    name: 'Pint',
    category: 'Beer',
    price: 100,
    availableInNoOfBars: 50,
  },
  {
    image: require('./assets/images/alcoholic-drinks.png'),
    name: 'Wine Canister',
    category: 'Wine',
    price: 6000,
    availableInNoOfBars: 10,
  },
  {
    image: require('./assets/images/arak.png'),
    name: 'Arak',
    category: 'Wine',
    price: 600,
    availableInNoOfBars: 12,
  },
  {
    image: require('./assets/images/beer.png'),
    name: 'Beer Mug',
    category: 'Beer',
    price: 150,
    availableInNoOfBars: 16,
  },
  {
    image: require('./assets/images/cocktail.png'),
    name: 'Cocktail',
    category: 'Sweet Drink',
    price: 200,
    availableInNoOfBars: 14,
  },
  {
    image: require('./assets/images/Barrel.png'),
    name: 'Beer Barrel',
    category: 'Beer',
    price: 200,
    availableInNoOfBars: 6,
  },
  {
    image: require('./assets/images/twoGlassWine.png'),
    name: 'Red Wine',
    category: 'Wine',
    price: 800,
    availableInNoOfBars: 5,
  },
  {
    image: require('./assets/images/champane.png'),
    name: 'Champagne',
    category: 'Extra brut',
    price: 4000,
    availableInNoOfBars: 3,
  },
  {
    image: require('./assets/images/alcohol.png'),
    name: 'Pint',
    category: 'Beer',
    price: 100,
    availableInNoOfBars: 50,
  },
  {
    image: require('./assets/images/alcoholic-drinks.png'),
    name: 'Wine Canister',
    category: 'Wine',
    price: 6000,
    availableInNoOfBars: 10,
  },
  {
    image: require('./assets/images/arak.png'),
    name: 'Arak',
    category: 'Wine',
    price: 600,
    availableInNoOfBars: 12,
  },
  {
    image: require('./assets/images/beer.png'),
    name: 'Beer Mug',
    category: 'Beer',
    price: 150,
    availableInNoOfBars: 16,
  },
  {
    image: require('./assets/images/cocktail.png'),
    name: 'Cocktail',
    category: 'Sweet Drink',
    price: 200,
    availableInNoOfBars: 14,
  },
  {
    image: require('./assets/images/Barrel.png'),
    name: 'Beer Barrel',
    category: 'Beer',
    price: 200,
    availableInNoOfBars: 6,
  },
  {
    image: require('./assets/images/twoGlassWine.png'),
    name: 'Red Wine',
    category: 'Wine',
    price: 800,
    availableInNoOfBars: 5,
  },
  {
    image: require('./assets/images/champane.png'),
    name: 'Champagne',
    category: 'Extra brut',
    price: 4000,
    availableInNoOfBars: 3,
  },
  {
    image: require('./assets/images/alcohol.png'),
    name: 'Pint',
    category: 'Beer',
    price: 100,
    availableInNoOfBars: 50,
  },
  {
    image: require('./assets/images/alcoholic-drinks.png'),
    name: 'Wine Canister',
    category: 'Wine',
    price: 6000,
    availableInNoOfBars: 10,
  },
  {
    image: require('./assets/images/arak.png'),
    name: 'Arak',
    category: 'Wine',
    price: 600,
    availableInNoOfBars: 12,
  },
  {
    image: require('./assets/images/beer.png'),
    name: 'Beer Mug',
    category: 'Beer',
    price: 150,
    availableInNoOfBars: 16,
  },
  {
    image: require('./assets/images/cocktail.png'),
    name: 'Cocktail',
    category: 'Sweet Drink',
    price: 200,
    availableInNoOfBars: 14,
  },
  {
    image: require('./assets/images/Barrel.png'),
    name: 'Beer Barrel',
    category: 'Beer',
    price: 200,
    availableInNoOfBars: 6,
  },
  {
    image: require('./assets/images/twoGlassWine.png'),
    name: 'Red Wine',
    category: 'Wine',
    price: 800,
    availableInNoOfBars: 5,
  },
  {
    image: require('./assets/images/champane.png'),
    name: 'Champagne',
    category: 'Extra brut',
    price: 4000,
    availableInNoOfBars: 3,
  },
  {
    image: require('./assets/images/alcohol.png'),
    name: 'Pint',
    category: 'Beer',
    price: 100,
    availableInNoOfBars: 50,
  },
  {
    image: require('./assets/images/alcoholic-drinks.png'),
    name: 'Wine Canister',
    category: 'Wine',
    price: 6000,
    availableInNoOfBars: 10,
  },
  {
    image: require('./assets/images/arak.png'),
    name: 'Arak',
    category: 'Wine',
    price: 600,
    availableInNoOfBars: 12,
  },
  {
    image: require('./assets/images/beer.png'),
    name: 'Beer Mug',
    category: 'Beer',
    price: 150,
    availableInNoOfBars: 16,
  },
  {
    image: require('./assets/images/cocktail.png'),
    name: 'Cocktail',
    category: 'Sweet Drink',
    price: 200,
    availableInNoOfBars: 14,
  },
  {
    image: require('./assets/images/Barrel.png'),
    name: 'Beer Barrel',
    category: 'Beer',
    price: 200,
    availableInNoOfBars: 6,
  },
  {
    image: require('./assets/images/twoGlassWine.png'),
    name: 'Red Wine',
    category: 'Wine',
    price: 800,
    availableInNoOfBars: 5,
  },
  {
    image: require('./assets/images/champane.png'),
    name: 'Champagne',
    category: 'Extra brut',
    price: 4000,
    availableInNoOfBars: 3,
  },
  {
    image: require('./assets/images/alcohol.png'),
    name: 'Pint',
    category: 'Beer',
    price: 100,
    availableInNoOfBars: 50,
  },
  {
    image: require('./assets/images/alcoholic-drinks.png'),
    name: 'Wine Canister',
    category: 'Wine',
    price: 6000,
    availableInNoOfBars: 10,
  },
  {
    image: require('./assets/images/arak.png'),
    name: 'Arak',
    category: 'Wine',
    price: 600,
    availableInNoOfBars: 12,
  },
  {
    image: require('./assets/images/beer.png'),
    name: 'Beer Mug',
    category: 'Beer',
    price: 150,
    availableInNoOfBars: 16,
  },
  {
    image: require('./assets/images/cocktail.png'),
    name: 'Cocktail',
    category: 'Sweet Drink',
    price: 200,
    availableInNoOfBars: 14,
  },
  {
    image: require('./assets/images/Barrel.png'),
    name: 'Beer Barrel',
    category: 'Beer',
    price: 200,
    availableInNoOfBars: 6,
  },
  {
    image: require('./assets/images/twoGlassWine.png'),
    name: 'Red Wine',
    category: 'Wine',
    price: 800,
    availableInNoOfBars: 5,
  },
  {
    image: require('./assets/images/champane.png'),
    name: 'Champagne',
    category: 'Extra brut',
    price: 4000,
    availableInNoOfBars: 3,
  },
  {
    image: require('./assets/images/alcohol.png'),
    name: 'Pint',
    category: 'Beer',
    price: 100,
    availableInNoOfBars: 50,
  },
  {
    image: require('./assets/images/alcoholic-drinks.png'),
    name: 'Wine Canister',
    category: 'Wine',
    price: 6000,
    availableInNoOfBars: 10,
  },
  {
    image: require('./assets/images/arak.png'),
    name: 'Arak',
    category: 'Wine',
    price: 600,
    availableInNoOfBars: 12,
  },
  {
    image: require('./assets/images/beer.png'),
    name: 'Beer Mug',
    category: 'Beer',
    price: 150,
    availableInNoOfBars: 16,
  },
  {
    image: require('./assets/images/cocktail.png'),
    name: 'Cocktail',
    category: 'Sweet Drink',
    price: 200,
    availableInNoOfBars: 14,
  },
  {
    image: require('./assets/images/Barrel.png'),
    name: 'Beer Barrel',
    category: 'Beer',
    price: 200,
    availableInNoOfBars: 6,
  },
  {
    image: require('./assets/images/twoGlassWine.png'),
    name: 'Red Wine',
    category: 'Wine',
    price: 800,
    availableInNoOfBars: 5,
  },
  {
    image: require('./assets/images/champane.png'),
    name: 'Champagne',
    category: 'Extra brut',
    price: 4000,
    availableInNoOfBars: 3,
  },
  {
    image: require('./assets/images/alcohol.png'),
    name: 'Pint',
    category: 'Beer',
    price: 100,
    availableInNoOfBars: 50,
  },
  {
    image: require('./assets/images/alcoholic-drinks.png'),
    name: 'Wine Canister',
    category: 'Wine',
    price: 6000,
    availableInNoOfBars: 10,
  },
  {
    image: require('./assets/images/arak.png'),
    name: 'Arak',
    category: 'Wine',
    price: 600,
    availableInNoOfBars: 12,
  },
  {
    image: require('./assets/images/beer.png'),
    name: 'Beer Mug',
    category: 'Beer',
    price: 150,
    availableInNoOfBars: 16,
  },
  {
    image: require('./assets/images/cocktail.png'),
    name: 'Cocktail',
    category: 'Sweet Drink',
    price: 200,
    availableInNoOfBars: 14,
  },
  {
    image: require('./assets/images/Barrel.png'),
    name: 'Beer Barrel',
    category: 'Beer',
    price: 200,
    availableInNoOfBars: 6,
  },
  {
    image: require('./assets/images/twoGlassWine.png'),
    name: 'Red Wine',
    category: 'Wine',
    price: 800,
    availableInNoOfBars: 5,
  },
  {
    image: require('./assets/images/champane.png'),
    name: 'Champagne',
    category: 'Extra brut',
    price: 4000,
    availableInNoOfBars: 3,
  },
  {
    image: require('./assets/images/alcohol.png'),
    name: 'Pint',
    category: 'Beer',
    price: 100,
    availableInNoOfBars: 50,
  },
  {
    image: require('./assets/images/alcoholic-drinks.png'),
    name: 'Wine Canister',
    category: 'Wine',
    price: 6000,
    availableInNoOfBars: 10,
  },
  {
    image: require('./assets/images/arak.png'),
    name: 'Arak',
    category: 'Wine',
    price: 600,
    availableInNoOfBars: 12,
  },
  {
    image: require('./assets/images/beer.png'),
    name: 'Beer Mug',
    category: 'Beer',
    price: 150,
    availableInNoOfBars: 16,
  },
  {
    image: require('./assets/images/cocktail.png'),
    name: 'Cocktail',
    category: 'Sweet Drink',
    price: 200,
    availableInNoOfBars: 14,
  },
];
